name: gwas_harm
channels:
  - bioconda
dependencies:
 - tabix
 - python==3.9.10
 - pip==21.3.1
 - pip:
        - appdirs==1.4.4
        - attrs==19.3.0
        - certifi==2020.4.5.1
        - chardet==3.0.4
        - ConfigArgParse==1.2.3
        - datrie==0.8.2
        - decorator==4.4.2
        - docutils==0.16
        - gitdb==4.0.5
        - GitPython==3.1.2
        - gwas-sumstats-tools==1.0.22
        - idna==2.9
        - importlib-metadata==1.6.0
        - ipython-genutils==0.2.0
        - jsonschema==3.2.0
        - nbformat==5.0.6
        - numpy==1.26.4
        - pandas==2.1.4
        - psutil==5.7.0
        - pyarrow
        - pyliftover==0.4
        - pyrsistent==0.16.0
        - pysam==0.18.0
        - python-dateutil==2.8.2
        - pytz==2020.1
        - PyYAML==5.3.1
        - ratelimiter==1.2.0.post0
        - requests==2.23.0
        - six==1.15.0
        - smmap==3.0.4
        - toposort==1.5
        - traitlets==4.3.3
        - urllib3==1.25.9
        - wrapt==1.12.1
        - zipp==3.1.0
        - duckdb==0.9.2